"""add contact services interested field

Revision ID: 0a4c3af88ceb
Revises: a6133d22040c
Create Date: 2026-02-16 18:20:47.334092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4c3af88ceb'
down_revision = 'a6133d22040c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services_interested', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_submissions', schema=None) as batch_op:
        batch_op.drop_column('services_interested')

    # ### end Alembic commands ###
